create table
  public.cars (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    make text not null,
    model text not null,
    year bigint not null,
    color text not null,
    constraint cars_pkey primary key (id)
  ) tablespace pg_default;